version: '3.1'

services:
  # mongo:
  #   image: mongo:5
  #   container_name: mongo
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:27017:27017"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
  #     MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

  # mongo-express:
  #   image: mongo-express
  #   depends_on:
  #     - mongo
  #   container_name: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - "127.0.0.1:7070:8081"
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: ${ME_CONFIG_MONGODB_ADMINUSERNAME}
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: ${ME_CONFIG_MONGODB_ADMINPASSWORD}
  #     ME_CONFIG_MONGODB_URL: ${ME_CONFIG_MONGODB_URL}

  bot:
    build: ./
    container_name: aternos-bot
    environment:
      DISCORD_TOKEN: ${DISCORD_TOKEN}
      ATERNOS_SESSION: ${ATERNOS_SESSION}
      ATERNOS_SERVER: ${ATERNOS_SERVER}
      MONGO_DB_URI: ${MONGO_DB_URI}
      PROXY: ${PROXY}
